export const QueryKeys = {
  MENU: "menu",
  CLUB: "club",
  IMAGE: "image",
  TABLE: "table",
  REVIEW: "review",
  PROFILE: "profile",
  LOCATION: "location",
  AUTH_DATA: "auth-data",
  AUTH_TYPE: "auth-type",
  GEOLOCATION: "geolocation",
  TRANSACTION: "transaction",
  SEARCH_HISTORY: "search-history",
  UPCOMING_BOOKING: "upcoming-booking",
  BOOKING_HISTORY: "booking-history",
  IS_AUTHENTICATED: "is-authenticated",
} as const;
